baseURL = "https://ltosp.uk/"
languageCode = "en-us"
title = "LT OSP Field Guide"
theme = ["lt-osp", "fuse-search"]

[outputFormats]
  [outputFormats.NetlifyRedirects]
    name = "_Redirects"
    baseName = "_redirects"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "_Redirects"]

[taxonomies]
  guild = "guilds"

[Params]
  themeColor = "theme-base-09"
  description = "An interactive pocket guide to the Lorien Trust Role-Playing (L.T.R.P.) System's Occupational Skill Points v4.01"
  copyright = "Copyright 2020 Adam Scott and Phill Sparks. All rights reserved."
  [Params.Redirects]
    Gone = []
    [Params.Redirects.Custom]
      "https://compassionate-aryabhata-ce7373.netlify.com/*" = "https://ltosp.uk/:splat"

[[menu.guilds]]
  name = "General"
  identifier = "misc"
  weight = -1

[[menu.guilds]]
  name = "Rune 2020"
  identifier = "rune-2020"
  weight = -1
