[build]
  publish = "public"
  command = "mkdir public; hugo --baseURL=$URL/"

[build.environment]
  HUGO_VERSION = "0.111.3"

[context.deploy-preview]
  command = "mkdir public; hugo --baseURL=$DEPLOY_PRIME_URL/"

[context.branch-deploy]
  command = "mkdir public; hugo --buildDrafts --baseURL=$DEPLOY_PRIME_URL/"
