[build]
publish = "public"
command = "rm -r public ; hugo --gc --minify --destination=public"

[context.production.environment]
HUGO_VERSION = "0.111.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "rm -r public ; hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL --destination=public"

[context.deploy-preview.environment]
HUGO_VERSION = "0.111.3"

[context.branch-deploy]
command = "rm -r public ; hugo --gc --minify -b $DEPLOY_PRIME_URL --destination=public"

[context.branch-deploy.environment]
HUGO_VERSION = "0.111.3"
