[build]
publish = "public"
command = "make production-build"

[build.environment]
HUGO_VERSION = "0.111.3"

[context.production.environment]
HUGO_BASEURL = "https://ltosp.uk/"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "make deploy-preview"

[context.branch-deploy]
command = "make branch-deploy"
